name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    uses: yutila-org/.github/.github/workflows/semgrep.yml@main
    
  syft:
    uses: yutila-org/.github/.github/workflows/sbom.yml@main
    with:
      target-path: '.'

  gitleaks:
    uses: yutila-org/.github/.github/workflows/secret-scan.yml@main