name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy:
    uses: yutila-org/.github/.github/workflows/trivy.yml@main
    
  sbom:
    uses: yutila-org/.github/.github/workflows/sbom.yml@main
    with:
      target-path: '.'

  secret-scan:
    uses: yutila-org/.github/.github/workflows/secret-scan.yml@main