name: Gitleaks

on:
  workflow_call:

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/code \
            zricethezav/gitleaks:latest \
            detect --source="/code" --verbose --report-format=sarif --report-path="/code/gitleaks.sarif"